export const symbols = [
  // Forex Pairs (50)
  "EURUSD", "USDJPY", "GBPUSD", "AUDUSD", "USDCAD", "USDCHF", "NZDUSD",
  "EURJPY", "GBPJPY", "EURGBP", "AUDJPY", "EURAUD", "EURCHF", "AUDNZD",
  "NZDJPY", "GBPAUD", "GBPCAD", "EURNZD", "AUDCAD", "GBPCHF", "AUDCHF",
  "EURCAD", "CADJPY", "GBPNZD", "USDSEK", "USDNOK", "USDSGD", "USDHKD",
  "USDTRY", "USDZAR", "USDINR", "USDMXN", "USDCNH", "EURSEK", "EURNOK",
  "EURSGD", "EURTRY", "EURZAR", "EURINR", "EURMXN", "EURCNH", "GBPSEK",
  "GBPNOK", "GBPSGD", "GBPTRY", "GBPZAR", "GBPINR", "GBPMXN", "GBPCNH",
  "USDCZK", "USDPLN",

  // Metals (5)
  "XAUUSD", "XAGUSD", "XPTUSD", "XPDUSD", "XAUEUR",

  // Indices (15)
  "US30", "UK100", "AUS200", 
  "FRA40", "HK50", "CHINA50", "NETH25", 

];